<a href="https://colab.research.google.com/github/Lu2077/Python-Math-s/blob/main/Rotation%26LinearTransformations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#MATRICES DE TRASLACION*ROTACION
#Definir una funcion dadas dos matrices calcule su multiplicacion-------
import sympy as sp
import pandas as pd
import numpy as np
import math

def sin(grados):
    return math.sin(math.radians(grados))
def cos(grados):
    return math.cos(math.radians(grados))


y_valor = float(input('ingrese el valor de y: '))
thita = float(input('ingrese el valor del ángulo thita: '))
thita_grados = math.radians(thita)
y = sp.symbols('y')
thita = sp.symbols('thita')

sin_thita = math.sin(thita_grados)
cos_thita = math.cos(thita_grados)


Hty = np.array([[1,0,0,0],
                [0,1,0,y_valor],
                [0,0,1,0],
                [0,0,0,1]])


Hrz = np.array([[cos_thita,-sin_thita,0,0],
                [sin_thita,cos_thita,0,0],
                [0,0,1,0],
                [0,0,0,1]])

print("Matriz de traslacion y: ")
print(Hty)
print("Matriz de rotación Z: ")
print(Hrz)

def matrizHtransformacao(Hty,Hrz):
    if len(Hty[0]) == len(Hrz):
        resultado = []
        #Iterar sobre las filas de la matriz Hty
        for i in range(len(Hty)):
            #inicializar una nueva fila en el resultado
            nueva_fila = []
        #Iterar sobre las columnas de Hrz
            for j in range(len(Hrz[0])):
                #Inicializar el valor del elemento en una nueva fila
                elemento_nuevo = 0
                #iterar sobre los elementos de la primera fila Hty y la p.columna Hrz
                for k in range(len(Hty[0])):
                    #multiplicar y sumar los elementos correspondientes
                    elemento_nuevo += Hty[i][k] * Hrz[k][j]
                #Agregar el nuevo elemento de la fila
                nueva_fila.append(elemento_nuevo)
                #agregar el nuevo elemento a la fila
            resultado.append(nueva_fila)
        return resultado
    else:
        print("Las dimensiones no son compatibles")
        return None
resultado = matrizHtransformacao(Hty,Hrz)
print("La matriz de transformación es: \n")
for fila in resultado:
    print(fila)







ingrese el valor de y: 5.0
ingrese el valor del ángulo thita: 45
Matriz de traslacion y: 
[[1. 0. 0. 0.]
 [0. 1. 0. 5.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matriz de rotación Z: 
[[ 0.70710678 -0.70710678  0.          0.        ]
 [ 0.70710678  0.70710678  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
La matriz de transformación es: 

[np.float64(0.7071067811865476), np.float64(-0.7071067811865475), np.float64(0.0), np.float64(0.0)]
[np.float64(0.7071067811865475), np.float64(0.7071067811865476), np.float64(0.0), np.float64(5.0)]
[np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0)]
[np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0)]
